### ISSUE TITLE
15k duplicate sequence names in ncov/open/aligned.fasta.xz

### ISSUE THREAD

**Issue by tsibley** [nextstrain/ncov-ingest#281] opened 2022-02-03 18:00 UTC
**Current Behavior**  
The current https://data.nextstrain.org/files/ncov/open/aligned.fasta.xz contains ~15k duplicated sequences.

I haven't checked if the sequences themselves are identical, but it seems that GenBank only has one record for a name I spot checked (`USA/DE-CDC-LC0461229/2022`). The metadata.tsv.gz does not contain duplicate strain names.

See https://discussion.nextstrain.org/t/error-in-augur-tree-duplicated-sequence-name/970/4 for full context that lead to this discovery.

@jameshadfield @ivan-aksamentov ISTR recent changes introduced incremental alignments? Is this possibly related? I can imagine how naive concatenation could result in this.

**Expected behavior**  
None of our sequence outputs (unaligned, aligned, etc) contain duplicated names and/or sequences.

**How to reproduce**  
```console
$ wget https://data.nextstrain.org/files/ncov/open/aligned.fasta.xz
$ xzcat -T4 < aligned.fasta.xz | grep '^>' | sort --parallel 4 | uniq -D > dups
```

`dups` ([see output](https://gist.githubusercontent.com/tsibley/5abfa876c6dd43c68bf3ef656deb17c1/raw/8b0bf45f0b524320fe8c32341d3bed06854747b1/dups)) will contain 30,926 lines, representing 15,463 names which appear twice in `aligned.fasta.xz`.

**Comment by ivan-aksamentov** [comment] 2022-02-03 22:31
That's pretty bad!

> ISTR recent changes introduced incremental alignments? Is this possibly related? I can imagine how naive concatenation could result in this.

I cannot think immediately what might have caused it. The concatenation of fasta is no different of concatenation of tsv, so in my view the dupes would have to appear simultaneously.

I haven't checked myself yet, but are the sequences appear in pairs, or in triplets, or n-uplets? If there's a concat bug, then it might have duplicated things more than once.

Note that the entire fasta is generated by the full run (7M sequences or so nowadays), and then only a relatively small portion at the end is added by the concatenation daily (~50k/day or so I think). It would be helpful to know whether the duplicates appear in the middle or in the end of the file - this might provide an indication of where to look for the mistake - in the daily or in full run. The last full run was on Jan 24, so ~500k sequences since then were appended, or 6% of the total (the numbers are very approximate). If duplicates are in the tail 6% of the file, the problem is specific to daily ingest.

Are the duplicated sequence names matching exactly? Could they differ by a trailing space or some unicode characters?

I have to disappear for a few days, but if not solved by then, I will investigate.

**Comment by corneliusroemer** [comment] 2022-02-04 00:03
I had a quick look by looking the metadata of the duplicated sequences. There `date_submitted` distribution could contain a clue, seems to have been a one day glitch, explaining why we haven't encountered the issue with GISAID (yet):

```
date_submitted  count
2022-01-24      15462
2021-06-30      1
```

Here's the metadata (it's tsv but ending changed for support by Github upload)
[dup_meta.txt](https://github.com/nextstrain/ncov-ingest/files/7999046/dup_meta.txt)

**Comment by ivan-aksamentov** [comment] 2022-02-04 05:07
Thanks for the investigation @corneliusroemer!

This might have happened if aligned.fasta was copied after full run, but nextclade.tsv was not. Or if it was otherwise reverted to the old state before the daily ingest on Jan 25.

The decision on whether a sequence is present in "cache" is made based on nextclade.tsv. So if fasta was updated with the sequences up to Jan 24, but the tsv was not, then during subsequent daily ingest nextclade would process the sequences from Jan 24 again and would append them happily creating duplicates.

In order to test this hypotheses, we need to:
 - make a full run to recompute the cache (I started a pair of runs just now: [1](https://github.com/nextstrain/ncov-ingest/actions/runs/1793325971), [2](https://github.com/nextstrain/ncov-ingest/actions/runs/1793326233))
 - make sure there are no duplicates in the resulting aligned.fasta and nextclade.tsv
 - meticulously copy all the 3 resulting files to prod, making sure no other concurrent processes are running to overwrite them, for clean experiment
 - make a daily run
 - make sure there are no duplicates in aligned.fasta, nextclade.tsv and metadata.tsv

It will take a while.

In the meantime we need to make sure there is no flaw in the diff/concat logic, by eyeballing the code.

If the dupes break upstream workflows and it's urgent, we may need to manually hotfix the aligned.fasta (using seqkit perhaps) and upload it to prod.

**Comment by corneliusroemer** [comment] 2022-02-04 05:47
Thanks for thinking up a plan!

To summarize your hypothesis: it's not a bug in the code but failure to copy nextclade.tsv after the last full run.

Shouldn't we be able to test this hypothesis easily because then the nextclade.tsv should lack the new columns introduced (reversions etc.)?

**Comment by ivan-aksamentov** [comment] 2022-02-07 16:36
Alright, I am back. Cornelius have released a new Nextclade Dataset, so I am running a new pair of fresh full runs. Will continue with the checklist after they are done.

**Comment by ivan-aksamentov** [comment] 2022-02-08 21:03
I finished the checklist, downloaded the new files after today's ingest at around 2022-02-08 20:58 UTC and ran the following commands to verify there are no duplicates:

```bash
$ pixz < aligned.fasta.xz | grep '^>' | cut -c 2- | sort --parallel $(nproc) | uniq -D > dups
$ wc -l dups
0 dups
$ pigz -cd metadata.tsv.gz | keep-header -- tsv-join -f dups -k 1 > dup_meta.tsv
$ wc -l dup_meta.tsv 
1 dup_meta.tsv
```
(dup_meta.tsv contains 1 line with the header)

Could you please double check on your side?

**Comment by sacundim** [comment] 2022-02-09 04:39
I ran my job whose failure prompted me to start [the discussion thread that led to this ticket](https://discussion.nextstrain.org/t/error-in-augur-tree-duplicated-sequence-name/970). It now succeeds without any workaround.

Thanks, guys!

**Comment by ivan-aksamentov** [comment] 2022-02-09 15:44
Great! I will close the issue then. Open a new one if there's any remaining problems.

**Closed by ivan-aksamentov** 2022-02-09 15:44 UTC
Labels: bug

**Comment by tsibley** [comment] 2022-02-10 18:58
@ivan-aksamentov  :raised_hands: for fixing this. Do you have an understanding of how it happened in the first place? Are there longer term structural changes that should happen here to avoid it happening again?

**Comment by tsibley** [comment] 2022-02-11 18:06
(3) is what I had in mind to make this robustly idempotent. I agree it may introduce too much slowness, but I wonder how much, though? Maybe it would be acceptable. A few extra minutes to ensure seqs are duplicated seems worth it. Sequence names are not guaranteed to be unique, but we (unfortunately) treat them as such ~everywhere including elsewhere in ncov-ingest currently.

I haven't checked the file contents, but it seems to me like the version history in S3 supports your conclusion about the mechanism for this bug. Normally there are couplets of an nextclade.tsv.gz update and then ~10 minutes later an aligned.fasta.xz update, but it stutters on 25 Jan (bolded):
|Key                               |LastModified              |VersionId                         |
|----------------------------------|--------------------------|----------------------------------|
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-28T18:21:15\.000Z|9h3TtadmDs2GsYuMKYiCWV\.rCqn7XOnl |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-28T18:11:09\.000Z|eTO5Ff6Ca7n7RAcig5MXmWRrBFGbrTsv  |
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-26T18:14:08\.000Z|AWMm4Bjy3cU7qK3JnJEDjVR4YUSwTBvc  |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-26T18:04:17\.000Z|gt8hYZKJ3oeRgQl\_UVg6CKLDBNAgvOtr |
|**files/ncov/open/aligned\.fasta\.xz**|**2022\-01\-25T21:35:53\.000Z**|G9XD\_yhtshXqw3Stf8\_\_YeykT7Ait08i|
|**files/ncov/open/aligned\.fasta\.xz**|**2022\-01\-25T17:30:05\.000Z**|\_\.odPGccmL4qKjUhvT4edBQ3GOAdDzxZ|
|**files/ncov/open/nextclade\.tsv\.gz**|**2022\-01\-25T17:20:45\.000Z**|YjbHJtX\.nxiS95H1fyeTDQr\.aK\.81AGX|
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-25T07:14:35\.000Z|r\_zveh20mZs\.CSQVh7B\_052ODziSrtcT|
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-25T07:10:51\.000Z|d5S\.u5bP6P2edytgcopXNNPgZULXiKvi |
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-24T19:10:10\.000Z|7UGA\_rTyraJapXjGEn2Uq7x1VsGHu5XA |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-24T19:00:30\.000Z|1vq5\_JSrCsiR1uFCC0SP6uvZDsmoyK8F |
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-23T20:41:02\.000Z|eTKVY\.KrOIYPE1lXDzqA2QZKopuwdxNN |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-23T20:31:37\.000Z|0fUWU6rvWMwwmRpV\.YULDBzAQTBxFnND |
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-22T21:22:03\.000Z|OP4dTO0uZTL3xA5cohLf72LqVmh2VFw3  |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-22T21:12:28\.000Z|sRNkA6mrItTl\_Z59WeDwpoMuCNT6wjv7 |
|files/ncov/open/aligned\.fasta\.xz|2022\-01\-21T17:49:23\.000Z|mN5ygJ7VeZJOqW8t6T1wdomc1wGfJvbw  |
|files/ncov/open/nextclade\.tsv\.gz|2022\-01\-21T17:40:00\.000Z|Wgx\.b4aoMWsGAnwwZvCf79\.CKoyA8JEX|

**Comment by tsibley** [comment] 2022-02-11 20:18
Can confirm that aligned.fasta.xz from 2022-01-25T21:35:53.000Z (`G9XD_yhtshXqw3Stf8__YeykT7Ait08i`) contains the dups reported here but the prior version from 2022-01-25T17:30:05.000Z (`_.odPGccmL4qKjUhvT4edBQ3GOAdDzxZ`) does not.

**Comment by sacundim** [comment] 2022-02-12 03:07
I don't know how helpful this information is, but when I used the workaround that deduplicates whole sequences (both by name and sequence), that step took about 33 minutes in an AWS Fargate X86 container, using this script:

* https://github.com/nextstrain/ncov/blob/44223bcd5249e53eb9a67fb2cc9f2efef77ff530/scripts/sanitize_sequences.py#L38

So maybe that's an upper bound on how much time it'd add to you pipeline? You be the judge.

**Comment by corneliusroemer** [comment] 2022-02-12 08:39
I agree it would be good to check for duplicate strain names.

Maybe we can just add a report/Slack message warning rather than make it part of ingest?

Once update for the day is done, start a script that checks for duplicates, then sends a warning if there are duplicates.

This should fire only very rarely in which case we can manually investigate.

Alternatively, deduplicating with seqkit should be very fast. Not take more than some 10 minutes. The slowest step when dealing with all sequences is decompressing the fasta.xz, which takes ~10min.

**Comment by joverlee521** [comment] 2022-04-20 19:52
A similar issue was reported today with duplicate sequence names in both the GISAID and the GenBank `aligned.fasta.xz` (see [Slack thread](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1650477316202089)). 

Here's my understanding of what happened (based on GenBank files):
1. Nextclade full run was started on April 12 before the ncov-ingest run, so it started from the `sequences.fasta.xz` that was generated on April 11. 
2. ncov-ingest ran as usual on April 12, adding new sequences to the `aligned.fasta.xz`. I confirmed the `aligned.fasta.xz` from April 12, 2022, 15:41:00 (UTC-07:00) (versioin id `605PLUzv.c4c_FwgeTh5aUBrA0D21n6E`) did __not__ contain any dups. 
3. After the nextclade run, the new `nextclade.tsv.gz` was updated at April 13, 2022, 10:35:52 (UTC-07:00) (version id `X1fWfA0zllokWUFWGDnaueb4gX4QCgLa`). There are no records of `aligned.fasta.xz` being updated at the same time. 
4. Because ncov-ingest updates `aligned.fasta.xz` based on sequences names in `nextclade.tsv.gz`, it appended the sequences from April 12 to `aligned.fasta.xz` __again__.  I confirmed the `aligned.fasta.xz` from April 13, 2022, 15:50:02 (UTC-07:00) (version id `9TwRaiy2WTUpK2RRnfyEJiwMCDAx_UDw`) __did__ contain the dups. 

I've kicked off full Nextclade runs again to give us a clean slate and will upload aligned.fasta + nextclade.tsv after confirming they do not contain dups.

**Comment by corneliusroemer** [comment] 2022-04-20 20:40
Oh no, this was me. Sorry, this had slipped my mind m. I was only aware we needed to avoid copying while ingest is running. Didn't know aligned needed to be copied, too.

We should edit instructions in the PR (something like number 218, will check) that explains how to update after full run, mention that aligned.fasta.xz needs to be copied too, not just the nextclade.tsv.gz

We could also add seqkit dedup to ingest but that's extra work.

Instead of doing a full run and copying, could we not just delete the cache (align, nextclade.tsv etc) and then ingest would do the full run and save in right place in one go, making copying unnecessary? @ivan-aksamentov

**Comment by ivan-aksamentov** [comment] 2022-04-20 22:36
@corneliusroemer 

> Instead of doing a full run and copying, could we not just delete the cache (align, nextclade.tsv etc) and then ingest would do the full run and save in right place in one go, making copying unnecessary?

That's how it was done at some point (before the first million on GISAID). But daily ingest runs on a 16-core machine with 32 Gb of RAM, so it will take a while now (a few days probably).

**Comment by ivan-aksamentov** [comment] 2022-04-20 22:42
> We should edit instructions in the PR (something like number 218, will check) that explains how to update after full run, mention that aligned.fasta.xz needs to be copied too, not just the nextclade.tsv.gz

Perhaps a better instruction will be to "copy everything" from that directory.

**Comment by corneliusroemer** [comment] 2022-04-21 12:49
Oh ok, got it - so our machine setup is different for full run to make it finish faster.

In that case yeah, let's just change directions to say: copy everything.
