### ISSUE TITLE
compressed data error: bad block header magic after download

### ISSUE THREAD

**Issue by pvanheus** [nextstrain/ncov-ingest#286] opened 2022-02-25 13:31 UTC
**Current Behavior**  
After running `bin/fetch-from-gisaid` I get an error message: `lbzip2: "data/gisaid.ndjson.new.bz2": compressed data error: bad block header magic` (full log below). This is after download reported "(OK): download completed". At the point of the error message the files downloaded and (partially) unpacked:

```
-rw-r--r-- 1 pvh editors 260053049344 Feb 25 10:22 gisaid.ndjson.new
-rw-r--r-- 1 pvh editors  21112070822 Feb 25 07:24 gisaid.ndjson.new.bz2
```

**Expected behavior**  
I expected either:
1. the download completes and unpacks successfully or
2. the download fails with an error (if the downloaded data is indeed corrupt)

**How to reproduce** 
Steps to reproduce the current behavior:  

This is the script that I use to fetch the data:
```
#!/bin/bash

#SBATCH -c 2
#SBATCH --mem=10G

set -e

cd /usr/people/pvh/ncov-ingest 
source $HOME/miniconda3/bin/activate 
GISAID_API_ENDPOINT=ENDPOINT_URL
GISAID_USERNAME_AND_PASSWORD=XXXX:YYYY 
export GISAID_API_ENDPOINT GISAID_USERNAME_AND_PASSWORD
# this doesn't need pipenv anymore
bin/fetch-from-gisaid data/gisaid.ndjson.new 
pipenv run bin/transform-gisaid data/gisaid.ndjson.new
``` 

1. Run this script
2. Wait
3. See error

**Possible solution**  
(optional)  

**Your environment:**
 - Operating system:  Ubuntu 20.04

**Additional context**  

Complete log:

```

02/25 05:23:54 [NOTICE] Downloading 1 item(s)
[#a2d0d9 0B/0B CN:1 DL:0B]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:2.3MiB ETA:2m49s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:17MiB ETA:21s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:26MiB ETA:12s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:29MiB ETA:9s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:24MiB ETA:11s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:17MiB ETA:15s]
[#a2d0d9 19GiB/19GiB(98%) CN:8 DL:19MiB ETA:11s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:21MiB ETA:8s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:25MiB ETA:5s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:23MiB ETA:5s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:21MiB ETA:5s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:25MiB ETA:2s]
[#a2d0d9 19GiB/19GiB(99%) CN:8 DL:26MiB]
[#a2d0d9 19GiB/19GiB(100%) CN:0]

02/25 05:24:14 [NOTICE] Download complete: /usr/people/pvh/ncov-ingest/data/gisaid.ndjson.new.bz2

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a2d0d9|OK  |    24MiB/s|/usr/people/pvh/ncov-ingest/data/gisaid.ndjson.new.bz2

Status Legend:
(OK):download completed.
lbzip2: "data/gisaid.ndjson.new.bz2": compressed data error: bad block header magic
```

**Comment by pvanheus** [comment] 2022-02-25 18:40
This bug seems to be peculiar to download from GISAID when there is already a downloaded copy of GISAID in the destination directory. I.e. it seems that the download process either appends or otherwise modifies the GISAID `gisaid.ndjson.new.bz2` that causes the unpacking step to fail. 

I realise that this package isn't intended for people outside the Nextstrain core but it is *very* useful!

**Comment by jameshadfield** [comment] 2022-03-02 21:01
Hi @pvanheus -- I'd recommend making sure a previous ndjson (complete or incomplete) was removed before running the [fetch-from-gisaid](https://github.com/nextstrain/ncov-ingest/blob/761398c2cb1a89e0b85a74c471685508a5fc010d/bin/fetch-from-gisaid) script. This script exits with a non-zero code in most situations (as we use this to determine if we need to [rerun this command](https://github.com/nextstrain/ncov-ingest/blob/master/Snakefile#L36-L49)). However before rerunning we cleanup any created file (`rm {output.ndjson}`), so it's possible you are running into unexpected behavior here. Could you switch to the following?

```
rm -f data/gisaid.ndjson.new && bin/fetch-from-gisaid data/gisaid.ndjson.new 
```

**Comment by tsibley** [comment] 2022-03-21 23:08
@pvanheus `from-from-gisaid` uses `aria2c` to download over multiple connections simultaneously and also pick up where it left off from a partial download. So it's quite possible there's an edge case where an existing file is incorrectly resumed (or impossible to resume correctly because of remote vs. local drift in the meantime).

**Comment by trvrb** [comment] 2022-07-30 00:19
Noting here that I'm currently reproducing this from downloading endpoint file `gisaid.ndjson.bz2` locally and then running `lbzip2 -cd gisaid.ndjson.bz2 >/dev/null` to yield:
```
lbzip2: "gisaid.ndjson.bz2": compressed data error: bad block header magic
```
This may just be a transient issue with the GISAID endpoint.

**Comment by tsibley** [comment] 2022-08-01 17:04
@trvrb and I discussed more on Friday [in Slack](https://bedfordlab.slack.com/archives/CTZKJC7PZ/p1659135341194389) and concluded what we were seeing was likely a transient issue on GISAID's end (e.g. they were actually serving a truncated file, belied by the Content-Length being 13GiB instead of 30GiB). And indeed, the next update yesterday fixed it.

**Comment by tsibley** [comment] 2022-08-01 17:05
Closing this as I suspect the original issue was a similar truncation issue upstream.

**Closed by tsibley** 2022-08-01 17:05 UTC
Labels: bug
